PRAGMA foreign_keys = ON;

CREATE TABLE users(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  email VARCHAR(40) NOT NULL,
  firstname VARCHAR(20) NOT NULL,
  lastname VARCHAR(20) NOT NULL,
  password VARCHAR(256) NOT NULL,
  streak INTEGER NOT NULL DEFAULT 0
);

CREATE TABLE messages(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  message VARCHAR(512) NOT NULL,
  user INTEGER NOT NULL,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  room INTEGER NOT NULL,
  FOREIGN KEY (user) REFERENCES users(id) ON DELETE CASCADE
);

CREATE TABLE rooms(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT
);

CREATE TABLE users_to_rooms (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  user INTEGER NOT NULL,
  room INTEGER NOT NULL,
  color INTEGER NOT NULL,
  FOREIGN KEY (user) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (room) REFERENCES rooms(id) ON DELETE CASCADE
);

CREATE TABLE articles(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  title VARCHAR(128) NOT NULL,
  publisher VARCHAR(128) NOT NULL,
  tag VARCHAR(64) NOT NULL,
  image_url VARCHAR(256) NOT NULL,
  url VARCHAR(256) NOT NULL,
  created DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE trophies(
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  earnedURL VARCHAR(256) NOT NULL,
  unearnedURL VARCHAR(256) NOT NULL,
  description VARCHAR(256) NOT NULL
);

CREATE TABLE users_to_trophies (
  id INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
  user INTEGER NOT NULL,
  trophy INTEGER NOT NULL,
  FOREIGN KEY (user) REFERENCES users(id) ON DELETE CASCADE,
  FOREIGN KEY (trophy) REFERENCES trophies(id) ON DELETE CASCADE
);